run:
  concurrency: 4
  deadline: 3m
  issues-exit-code: 0
  tests: true
  #skip-dirs # vendor & generated files are skipped by default
  
output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - lll
  fast: false

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  misspell:
    locale: UK
